### ISSUE TITLE
Continue even if some PRs fails

### ISSUE THREAD

**Issue by Borda** [chinthakagodawita/autoupdate#100]
Hi @chinthakagodawita,
I have a follow-up question to #19 it seems that after trying to work forked PR which is very common in opensource the bot just dies, right? so even there are other PR it could resolve it just stop with reaching the first difficult PR...
So would it be possible to change this error as a warning (eventually add an argument such as "continue-if-fails") and continue with other PRs?
just for the record: https://github.com/PyTorchLightning/pytorch-lightning/pull/5451
and build: https://github.com/PyTorchLightning/pytorch-lightning/runs/1686819251?check_suite_focus=true#step:3:88

**Comment by chinthakagodawita** [comment]
Ouch, good find @Borda - should have this fixed, hopefully within the next week!

**Comment by chinthakagodawita** [comment]
Hey @Borda - this should be fixed by #102 which has just been released as part of [v1.1.0](https://github.com/chinthakagodawita/autoupdate/releases/tag/v1.1.0)
