### ISSUE TITLE
Add support for 'schedule' event

### ISSUE THREAD

**Issue by anarast** [chinthakagodawita/autoupdate#139]

**Comment by chinthakagodawita** [comment]
This should be easier now that event data typings are in as part of #147

**Comment by chinthakagodawita** [comment]
Hey @RishabhJain2018 sorry for the delay on this - `schedule` event support has just been released in [v1.4.0](https://github.com/chinthakagodawita/autoupdate/releases/tag/v1.4.0) 🎉
