### ISSUE TITLE
Feature Request: Option to exclude draft PRs

### ISSUE THREAD

**Issue by pjohnmeyer** [chinthakagodawita/autoupdate#176]
Would you be open to a PR that adds the following option?

* `EXCLUDE_DRAFTS`: When `"true"`, merge/update operations are not performed on draft pull requests. Defaults to `"false"`.

**Comment by chinthakagodawita** [comment]
Absolutely, contributions are very welcome!

What do you think about calling this `PR_TYPE` instead? And have it take one of three options: `'all'` (default), `'draft'` or `'full'`?

**Comment by pjohnmeyer** [comment]
Sure, although I’d like to brainstorm the name a little. What about `PR_READY_STATE` with options `all`, `ready` (or the perhaps clearer `ready_for_review`), and `draft`? `full` doesn’t immediately map to a GitHub concept for me when I read it.

**Comment by chinthakagodawita** [comment]
I like it, `PR_READY_STATE` it is, I'm all for being more verbose with config so lets do `ready_for_review` over `ready`.

> `full` doesn’t immediately map to a GitHub concept for me when I read it.

Yea ha - I was struggling a little with naming there.
