### ISSUE TITLE
Feature request: Add release as a trigger event

### ISSUE THREAD

**Issue by crflynn** [chinthakagodawita/autoupdate#204]
I recently added this to a project which has CI automation that bumps the project version and pushes a new commit + release via a bot to the repo with every merged PR. This commit is always published with `[skip ci]` so that the bot commits don't trigger new bot commits. The `[skip ci]` however prevents the autoupdater from running on those commits. I'm wondering if you would be willing to add `release` as a trigger event as a workaround?

**Comment by chinthakagodawita** [comment]
Hey @crflynn - I'm not sure `release` would be useful as a general trigger for something like autoupdate. 

You should be able to get this working by triggering autoupdate manually via a `workflow_dispatch` event, e.g. using something like https://github.com/marketplace/actions/dispatch-action

Either that or see if you can get the release bot to not add `[skip ci]`. e.g. semantic-release lets you configure the release commit message: https://github.com/semantic-release/git
