### ISSUE TITLE
Feature request - Add support for workflow dispatch event

### ISSUE THREAD

**Issue by bcapdevilac** [chinthakagodawita/autoupdate#262]
We're using autoupdate as `schedule` but we also want to set up the option to be able to trigger it manually, using `workflow_dispatch` event type.

However, we see this is currently unsupported and it's giving an error:
```
Error: Unknown event type 'workflow_dispatch', only 'push', 'pull_request', 'workflow_run', and 'schedule' are supported.
```

Are there any plans to support this event type? This would be very helpful for our current set up.

**Comment by chinthakagodawita** [comment]
Hey @bcapdevilac, no plans yet but it's a great idea. I'll put this in the backlog
