### ISSUE TITLE
Non-docker version?

### ISSUE THREAD

**Issue by mosherc** [chinthakagodawita/autoupdate#285]
Is there a way we can get a non-docker version? Using docker does not seem to be the norm for GitHub Actions, and there is some inherent risk with using a third party docker image. GitHub themselves suggest there is a higher risk for these actions saying:

> Warning: When creating workflows and actions, you should always consider whether your code might execute untrusted input from possible attackers. Certain contexts should be treated as untrusted input, as an attacker could insert their own malicious content. For more information, see "[Understanding the risk of script injections](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections)."

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

> To protect your code and data, we strongly recommend you verify the integrity of the Docker container image from Docker Hub before using it in your workflow.

https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#referencing-a-container-on-docker-hub

**Comment by chinthakagodawita** [comment]
Hey @mosherc, this is being tracked in #283
