### ISSUE TITLE
"::error::The path argument must be of type string" occurs when run auto-update bot locally and on Docker desktop environment.

### ISSUE THREAD

**Issue by munkherdeneen** [chinthakagodawita/autoupdate#324]
Hello Dear,

I am trying to run the auto-pull bot locally for using it in my private environment. Also, Trying to run it local docker desktop.

But, both local and docker run fail with the same error:

![image](https://user-images.githubusercontent.com/55971205/181109025-f4e05be6-5cb8-4edc-bcf8-c4d42fd9c3a9.png)

![image](https://user-images.githubusercontent.com/55971205/181109086-b4f349de-136c-4df9-8de6-dc7bbac61fbc.png)

1. Could you advise how can I make the action-bot run in locally and a local docker container? Should I create my own .env variables in this case?
2. Is it possible to use an action-bot for the GitHub Enterprise?

**Comment by chinthakagodawita** [comment]
Unfortunately local use of autoupdate isn't supported at this time.

> Is it possible to use an action-bot for the GitHub Enterprise?

I don't have access to a self-hosted Github Enterprise environment so I'm not too sure unfortunately.
