### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by TenSt** [chinthakagodawita/autoupdate#355]
Is there a plan to release the latest version from the main branch? Docs says that the `workflow_dispatch` event is supported, but I see that the PR that adds this support was merged after the latest release.

**Comment by chinthakagodawita** [comment]
Sorry for the delay on this, I haven't had a chance to work on this in a while! I'm aiming to get this project updated and will cut a release soon

**Comment by chinthakagodawita** [comment]
Version `v1.7.0` has just been released: https://github.com/chinthakagodawita/autoupdate/releases/tag/v1.7.0
